
[web]
servera ansible_ssh_host=172.25.250.10

[dns]
servera ansible_ssh_host=172.25.250.10

[db]
serverb ansible_ssh_host=172.25.250.11

[nfs]
serverb ansible_ssh_host=172.25.250.11

[email]
servera ansible_ssh_host=172.25.250.10

[storage]
serverb ansible_ssh_host=172.25.250.11

[all:vars]
ansible_user=devops
