---

- name: Remove immutable attribute from resolv.conf if present
  ansible.builtin.command: chattr -i /etc/resolv.conf
  changed_when: false
  failed_when: false
  
- name: Deploy resolv.conf on hosts
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
